apiVersion: v1
kind: Pod
metadata:
  name: combined-probes-demo
spec:
  containers:
  - name: myapp-container
    image: nginx
    # livenessProbe:
    #   httpGet:
    #     path: /healthz
    #     port: 80
    #   initialDelaySeconds: 10
    #   periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /ready
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5